version: '3.1'
services:
  # ---------------------------------------------------
  # RABBITMQ
  # ---------------------------------------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    networks: 
      lb4_network: 
        ipv4_address: '192.168.17.4'
    ports:
      - '5672:5672'
      - '15672:15672'
  # ---------------------------------------------------
  # CLIENT
  # ---------------------------------------------------
  client:
    build: ./flask_app
    ports:
      - '13000:${GUNICORN_PORT}'
    volumes:
      - './flask_app/client:/app'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      # SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
  # ---------------------------------------------------
  # DELIVERY
  # ---------------------------------------------------
  delivery:
    build: ./flask_app
    ports:
      - '14000:${GUNICORN_PORT}'
    volumes:
      - './flask_app/delivery:/app'
    networks: 
      lb4_network: 
        ipv4_address: '${DELIVERY_IP}'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      # SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
  # ---------------------------------------------------
  # MACHINE
  # ---------------------------------------------------
  machine:
    build: ./flask_app
    ports:
      - '15000:${GUNICORN_PORT}'
    volumes:
      - './flask_app/machine:/app'
    networks: 
      lb4_network: 
        ipv4_address: '${MACHINE_IP}'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      # SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
  # ---------------------------------------------------
  # ORDER
  # ---------------------------------------------------
  order:
    build: ./flask_app
    ports:
      - '16000:${GUNICORN_PORT}'
    volumes:
      - './flask_app/order:/app'
    networks: 
      lb4_network: 
        ipv4_address: '${ORDER_IP}'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      # SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
  # ---------------------------------------------------
  # PAYMENT
  # ---------------------------------------------------
  payment:
    build: ./flask_app
    ports:
      - '17000:${GUNICORN_PORT}'
    volumes:
      - './flask_app/payment:/app'
    networks: 
      lb4_network: 
        ipv4_address: '${PAYMENT_IP}'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      # SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
  # ---------------------------------------------------
  # HAPROXY
  # ---------------------------------------------------
  haproxy:
    build: ./flask_app/haproxy
    ports:
      - '${HAPROXY_PORT}:${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}'
    expose:
      - '${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}'
    environment:
      - 'CLIENT_IP=${CLIENT_IP}'
      - 'CLIENT_PORT=${GUNICORN_PORT}'
      - 'DELIVERY_IP=${DELIVERY_IP}'
      - 'DELIVERY_PORT=${GUNICORN_PORT}'
      - 'ORDER_IP=${ORDER_IP}'
      - 'ORDER_PORT=${GUNICORN_PORT}'
      - 'MACHINE_IP=${MACHINE_IP}'
      - 'MACHINE_PORT=${GUNICORN_PORT}'
      - 'PAYMENT_IP=${PAYMENT_IP}'
      - 'PAYMENT_PORT=${GUNICORN_PORT}'
      - 'HAPROXY_PORT=${HAPROXY_PORT}'
      - 'HAPROXY_STATS_PORT=${HAPROXY_STATS_PORT}'
    restart: unless-stopped
  # ---------------------------------------------------
  # DATABASE
  # ---------------------------------------------------
  db:
    image: mysql
    restart: always
    ports:
      - '13306:${MYSQL_PORT}'
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
networks:
  lb4_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'

